export EZ80_CLANG_TOOLCHAIN_VERSION="0.0.5"
export EZ80_CLANG_TOOLCHAIN_BUILDER="dinoboards/llvmez80-builder:${EZ80_CLANG_TOOLCHAIN_VERSION}"
export EZ80_CLANG_TOOLCHAIN_IMAGE="dinoboards/llvmez80:${EZ80_CLANG_TOOLCHAIN_VERSION}"

export EZ80_CLANG_TOOLCHAIN_BUILDER_PREV="dinoboards/llvmez80-builder:0.0.4"
export EZ80_CLANG_TOOLCHAIN_IMAGE_PREV="dinoboards/llvmez80:0.0.4"

