name: clang-tool-chain

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

permissions:
  contents: write  # Ensure the GITHUB_TOKEN has write permissions for contents

jobs:
  clang-tool-chain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Source version.sh and set environment variables
        id: set-env-vars
        run: |
          source ./version.sh
          echo "EZ80_CLANG_TOOLCHAIN_VERSION=$EZ80_CLANG_TOOLCHAIN_VERSION" >> $GITHUB_ENV
          echo "EZ80_CLANG_VERSION=$EZ80_CLANG_VERSION" >> $GITHUB_ENV
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo VERSION: $EZ80_CLANG_VERSION

      - name: download llvm for ez80
        run: make download-llvm-release

      - name: compile runtime
        run: make

      - name: package clang and runtime
        run: make package

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          RELEASE_NAME="Clang Release $TAG_NAME"
          CHANGELOG_URL="https://github.com/dinoboards/ez80-clang/compare/${LATEST_TAG}...${TAG_NAME}"
          gh release create $TAG_NAME "ez80-clang-${{ env.EZ80_CLANG_VERSION }}.tar.gz" --repo ${{ github.repository }} --title "$RELEASE_NAME" --prerelease --notes "**Full Changelog**: $CHANGELOG_URL"
