name: clang-tool-chain

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  clang-tool-chain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Source version.sh and set environment variables
        id: set-env-vars
        run: |
          source ./version.sh
          echo "EZ80_CLANG_TOOLCHAIN_VERSION=$EZ80_CLANG_TOOLCHAIN_VERSION" >> $GITHUB_ENV
          echo "EZ80_CLANG_VERSION=$EZ80_CLANG_VERSION" >> $GITHUB_ENV

      - name: package clang and runtime
        run: |
          make download-llvm-release
          make
          make package

      - name: zip-package
        uses: actions/upload-artifact@v4
        with:
          name: ez80-clang-${{ env.EZ80_CLANG_VERSION }}
          path: |
            tmp/direct

      - name: tar-gz-package
        uses: actions/upload-artifact@v4
        with:
          name: ez80-clang-package.tar.gz
          path: ez80-clang-${{ env.EZ80_CLANG_VERSION }}.tar.gz
